export const sampleMovies = [
  {
    id: "m1",
    title: "Todo en todas partes al mismo tiempo",
    year: 2024,
    rating: "TV-14",
    duration: "1h 58m",
    description:
      "Una heroína inesperada debe usar sus nuevos poderes para luchar contra los desconcertantes peligros del multiverso y así lograr salvar su mundo.",
    tags: ["Acción", "Espías"],
    image: "/shadow-protocol-movie-poster.png",
    poster: "/shadow-protocol-movie-poster.png",
  },
  {
    id: "m2",
    title: "Star Wars",
    year: 2023,
    rating: "PG-13",
    duration: "2h 10m",
    description: "Obi-Wan Kenobi es un joven aprendiz caballero Jedi bajo la tutela de Qui-Gon Jinn",
    tags: ["Sci‑Fi", "Aventura"],
    image: "/star_wars.png",
    poster: "/star_wars.png",
  },
  {
    id: "m3",
    title: "Midsomar",
    year: 2022,
    rating: "R",
    duration: "1h 42m",
    description: "Una pareja de estadounidenses acude con unos amigos a Midsommar, un festival de verano que se celebra cada 90 años en una aldea remota de Suecia.",
    tags: ["Drama", "Noir"],
    image: "/midsomar.png",
    poster: "/midsomar.png",
  },
  {
    id: "m4",
    title: "Spider-Man 2",
    year: 2004,
    rating: "TV-MA",
    duration: "8 eps",
    description: "Peter Parker lucha por equilibrar su vida personal con sus responsabilidades como Spider-Man, mientras enfrenta a un nuevo y peligroso enemigo, el Dr. Octopus.",
    tags: ["Pelicula", "Super heroes"],
    image: "/spider-man-2.png",
    poster: "/spider-man-2.png",
  },
  {
    id: "m5",
    title: "Drive",
    year: 2011,
    rating: "PG-13",
    duration: "2h 05m",
    description: "Un doble de cine de Hollywood que trabaja como conductor para criminales empieza a recibir amenazas de muerte después de un robo fallido.",
    tags: ["Acción"],
    image: "/drive.png",
    poster: "/drive.png",
  },
]
